<?php
require_once('GLOBALS.php');
require_once('Kom.php');
require_once('Request/Item.php');
require_once('Request/Pay.php');
require_once('Request/Request.php');
require_once('Response/ErrorResponse.php');
require_once('Response/TaxItem.php');
require_once('Response/Response.php');
require_once('Status/TaxRate.php');
require_once('Status/TaxCategory.php');
require_once('Status/TaxRates.php');
require_once('Status/Status.php');